  [build]                                                                                                                                                                                                   
  builder = "nixpacks"
                                                                                                                                                                                                            
  [deploy]        
  startCommand = "pip install . && python server.py"
